screen_width  = 800
screen_height = 600
screen_title = "Simple OpenGL C (k) Engine"
fullscreen = false
grab_mouse = false
default_scene = "space_scene"
proctri_tex = "grass.png"
tex_scale = 4
gpu_tiles = true